# Generated by Django 6.0.6 on 2026-06-16 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='complaint',
            name='call',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='complaint',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='complaint',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='complaint',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_add',
            field=models.BooleanField(default=True, verbose_name='Complaint: Add'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_delete',
            field=models.BooleanField(default=False, verbose_name='Complaint: Delete'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_edit',
            field=models.BooleanField(default=True, verbose_name='Complaint: Edit'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_view',
            field=models.BooleanField(default=True, verbose_name='Complaint: View'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='region',
            field=models.CharField(choices=[('North India', 'North India'), ('East India', 'East India'), ('West India', 'West India'), ('South India', 'South India'), ('Middle East', 'Middle East')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='registration_date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Case Locked', 'Case Locked'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Replaced', 'Replaced'), ('Reopen', 'Reopen'), ('Broken - Parts', 'Broken - Parts'), ('Broken - Technical Support', 'Broken - Technical Support'), ('Broken - Replacement', 'Broken - Replacement'), ('Abort', 'Abort'), ('Resolved after panel Replacement', 'Resolved after panel Replacement'), ('Workshop attention/Repair', 'Workshop attention/Repair'), ('Not Responded Calls', 'Not Responded Calls')], db_index=True, default='In Progress', max_length=40),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ticket_no',
            field=models.CharField(blank=True, db_index=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='region',
            field=models.CharField(blank=True, choices=[('North India', 'North India'), ('East India', 'East India'), ('West India', 'West India'), ('South India', 'South India'), ('Middle East', 'Middle East')], max_length=20),
        ),
    ]
