# Generated by Django 6.0.6 on 2026-06-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_complaint_options_complaint_call_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='region',
            field=models.CharField(choices=[('North India', 'North India'), ('East India', 'East India'), ('West India', 'West India'), ('South India', 'South India')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='region',
            field=models.CharField(blank=True, choices=[('North India', 'North India'), ('East India', 'East India'), ('West India', 'West India'), ('South India', 'South India')], max_length=20),
        ),
    ]
