# Generated by Django 6.0.6 on 2026-06-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_complaint_region_alter_employee_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
